### ISSUE TITLE
Documenting iid={{xmp.r['XMPieInstanceID']}}

### ISSUE THREAD

**Issue by westdigitalfr** [XMPieLab/XMPL-SDK#11]
Hello,

Would you like to add a word or two in the page

https://github.com/XMPieLab/XMPL-SDK/wiki/Cheat-Sheet-for-Email

regarding the

iid={{xmp.r['XMPieInstanceID']}}

feature. Only the XMPieRecipientKey is mentioned so far.

Thanks!

**Comment by morenoraf** [comment]
Hi

Since you are working with a Circle Template and an Instance via Campaign on Demand (CoD), then the best way to do it would be by using GetEnv in uPlan (or in uCreate Print, if you do not use uPlan separately). 

See here: 
https://help.xmpie.com/uPlan/v.9.8/Help/en/index.htm#t=QLingo%2FGetEnv_Functions.htm#XREF_75635_Instance_ID

Which means that you can create a text ADOR, for example, that is called InstanceIDADOR, and this would be its rule: 
GetEnv("InstanceID") 

In this example, your link in the email should look like this: 
http://domain/selfRegistration.html?iid={{InstanceIDADOR}}&rid={{xmp.r.XMPieRecipientKey}}
